THIS IS A TEST.

[build]
  publish = "public"
  command = "./scripts/build.sh"

[context.production.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "development"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "development"
  
