# Knative "production" Site Params (adds to (or can override) Site "config/_default")

# Only add Google Custom Search and Feedback links to "production"

# Create ID at https://cse.google.com/cse/
# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "008069654339966445896:nqydaxfpl7a"

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/knative/docs/issues/new/?title=Page%20is%20helpful&labels=kind%2Fmeta">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/knative/docs/issues/new/?title=Page%20needs%20improvement&labels=kind%2Fmeta">tell us how we can improve</a>.'

# Default docs params for "production" environment

# Production GitHub branch
latest_github_branch = "release-0.10"
# Default website version
version = "v0.10"

# Doc versions params
# Create a separate [[versions]] set for every version / doc set branch
# Use the ghbranchname param for specifying the GitHub branchname ->
# Example:
#   [thisisalink](https://github.com/.../tree/{{< params "ghbranchname" >}}/...)
#
# [[versions]] - Defines a single "version" of the Knative docs
#   version - Intuitive version label (ie. visible in menus)
#   ghbranchname - Name of branch of the doc version in GitHub
#                  (https://github.com/knative/docs/branches)
#   url - Fully qualified website URL to the doc version
#         (ie. https://www.knative.dev/[dirpath])
#   dirpath - The content folder name of the doc version
#           - Latest release is always set to "docs"
#           - Past/archived releases change to "v#.#-docs",
#             where # is the MAJOR and MINOR semantic version values

# Latest version
################
# Set to "docs" path

[[versions]]
  version = "v0.9"
  ghbranchname = "release-0.10"
  url = "/docs/"
  dirpath = "docs"

# Archived versions
###################
# Prefix all past versions with release # "v#.#-docs"

[[versions]]
  version = "v0.9"
  ghbranchname = "release-0.9"
  url = "/v0.9-docs/"
  dirpath = "v0.9-docs"

[[versions]]
  version = "v0.8"
  ghbranchname = "release-0.8"
  url = "/v0.8-docs/"
  dirpath = "v0.8-docs"

[[versions]]
  version = "v0.7"
  ghbranchname = "release-0.7"
  url = "/v0.7-docs/"
  dirpath = "v0.7-docs"

[[versions]]
  version = "v0.6"
  ghbranchname = "release-0.6"
  url = "/v0.6-docs/"
  dirpath = "v0.6-docs"

[[versions]]
  version = "v0.5"
  ghbranchname = "release-0.5"
  url = "/v0.5-docs/"
  dirpath = "v0.5-docs"

[[versions]]
  version = "v0.4"
  ghbranchname = "release-0.4"
  url = "/v0.4-docs/"
  dirpath = "v0.4-docs"

[[versions]]
  version = "v0.3"
  ghbranchname = "release-0.3"
  url = "/v0.3-docs/"
  dirpath = "v0.3-docs"

[[versions]]
  version = "v0.2"
  ghbranchname = "release-0.2"
  url = "https://github.com/knative/docs/tree/release-0.2"
  dirpath = "github-repo"

[[versions]]
  version = "v0.1"
  ghbranchname = "release-0.1"
  url = "https://github.com/knative/docs/tree/release-0.1"
  dirpath = "github-repo"

# Pre-release version
###################
# In-development (pre-release) content - "master" branch

[[versions]]
  version = "development"
  ghbranchname = "master"
  url = "/development/"
  dirpath = "development"

